# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Astro-SpaceElevator
version:      0.05
version_from: Astro/SpaceElevator.pm
installdirs:  site
requires:
    Astro::Coord::ECI:             0
    Math::MatrixReal:              2.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
